# Generated by Django 5.0.6 on 2024-12-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_user_apellido_user_dni_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
