# Generated by Django 5.0.6 on 2024-12-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='productos',
            new_name='detalles',
        ),
    ]
