# Generated by Django 5.0.6 on 2024-12-07 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_productos_popularidad'),
        ('ventas', '0002_rename_productos_venta_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='detalles',
            field=models.ManyToManyField(related_name='ventas', through='ventas.VentaDetalle', to='productos.productos'),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_detalles', to='ventas.venta'),
        ),
    ]
