# Generated by Django 5.0.6 on 2024-12-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_venta_detalles_alter_ventadetalle_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='detalles',
        ),
    ]
