# Generated by Django 5.0.6 on 2024-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_productos_popularidad'),
        ('ventas', '0004_remove_venta_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='detalles',
            field=models.ManyToManyField(related_name='ventas', through='ventas.VentaDetalle', to='productos.productos'),
        ),
    ]
