# Generated by Django 5.0.6 on 2025-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tiene_beneficio',
            field=models.BooleanField(default=False),
        ),
    ]
