# Generated by Django 5.0.6 on 2025-02-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_tiene_beneficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='tiene_beneficio',
        ),
    ]
