# Generated by Django 5.0.6 on 2025-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_remove_venta_tiene_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tiene_beneficio',
            field=models.BooleanField(default=False),
        ),
    ]
