# Generated by Django 5.0.7 on 2024-09-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='tags',
            field=models.ManyToManyField(related_name='productos', to='productos.tag'),
        ),
    ]
