# Generated by Django 5.0.7 on 2024-09-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_productos_imagen_productos_imagen_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='imagen_url',
            new_name='imagen',
        ),
    ]
