# Generated by Django 5.0.6 on 2024-12-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_productos_imagen'),
        ('productos', '0010_productos_imagen_url_alter_productos_imagen'),
    ]

    operations = [
    ]
