# Generated by Django 5.0.6 on 2024-12-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_merge_20241203_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='popularidad',
            field=models.IntegerField(default=0),
        ),
    ]
