# Generated by Django 5.0.6 on 2025-02-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_productovista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoVista',
        ),
    ]
